language: generic
sudo: required
services:
  - docker

install: true

before_script:
  - docker --version

script:
  - docker build -t johannweging/hubot-mattermost:latest ./

before_deploy:
  - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}

deploy:
  provider: script
  script: docker push johannweging/hubot-mattermost:latest
  on:
    all_branches: true
